---
- name: Example Playbook for Github Action Runner install
  hosts: all
  vars:
    runner_config_name: ubuntu-me
    runner_config_repo_url: url
    runner_config_labels: "label1,label2"
    runner_config_token: atoken
  roles:
    - role: ansible-github-action-runner
