---
- name: Configure Runner
  shell: |
    {{ runner_install_folder }}/config.sh --unattended --url {{ runner_config_repo_url }} --token {{ runner_config_token }} --name {{ runner_config_name }} --work {{ runner_work_folder }} --labels "{{ runner_config_labels | replace('', '-') }}"  --replace --runasservice
  when: runner_config_token | bool

- name: Run runner as service
  shell: |
    {{ runner_install_folder }}/svc.sh install
  when: runner_config_token | bool     
  become: true